# This enables the plugin to check for updates.
# If this is set to true and "auto-update" is set to false, you will only get notifications about updates.
# If don't want to check for updates, set this to false.
update-check: true

# This enables the plugin to download a new version if an update is detected.
# For this to work you have to set "update-check" to true.
# If you don't want to download updates automatically, set this to false.
auto-update: true

# If you want every hat to have its own permission, set this to true.
# The permission for the hat will be: 'crafthats.hat.HAT_NAME'
# The permission for all the hats is: 'crafthats.hat.*'
per-hat-permissions: true

metrics: true

# If you want the hats to cost ingame money, set this to true (requires Vault and an economy plugin).
economy: false

# An item that players use to open the hat menu.
hat-item: GLOWSTONE

# The hot-bar slot that the hat item will appear [1-9].
hat-item-slot: 9

hat-item-data-value: 0

hat-item-name: "&c&lHat selector"

# If you want players to be able to move the hat item in their inventory, set this to true
# The players will still be able to move the item if they are on creative mode.
can-move-hat-item: false

# If you want players to be able to drop the hat item, set this to true
can-drop-hat-item: false

# If you want to give players the hat item when they join the server, set this to true.
give-hat-item: true

chat-prefix: "&8[&3CraftHats&8]"

hat-menu-title: "Hats menu"

no-permission-message: "You don't have permission for this hat!"

reset-hat-message: "Type '/hats reset' to reset your hat!"

buy-hat-message: "You bought a new hat!"

wear-hat-message: "Enjoy your new hat!"

cant-afford-hat-message: "You can't afford that hat!"

already-own-hat-message: "You already own that hat!"

damage-message: "You took damage, so your hat has been reset!"