# This enables the plugin to check for updates.
# If this is set to true and "auto-update" is set to false, you will only get notifications about updates.
# If don't want to check for updates, set this to false.
update-check: true

# This enables the plugin to download a new version if an update is detected.
# For this to work you have to set "update-check" to true.
# If you don't want to download updates automatically, set this to false.
auto-update: false

# If you want every hat to have its own permission, set this to true.
# The permission for the hat will be: 'crafthats.hat.HAT_NAME'
# The permission for all the hats is: 'crafthats.hat.*'
per-hat-permissions: true

metrics: true