name: CraftHats
main: me.crafthats.Main
version: 1.1
description: Hat shop plugin for bukkit
depend: [Vault]
permissions:
  crafthats.admin:
    description: Gives access to all CraftHats features
    children:
      crafthats.*: true
      crafthats.use: true
      crafthats.hat.*: true
    default: op
  crafthats.use:
    description: Gives access to the CraftHats menu
    default: true
  crafthats.hat.*:
    description: Gives access to all hats
    default: op